; AUTO-GENERATED by tools/gen_forwards.py -- do not edit
; One naked trampoline per forwarded export.
EXTERN g_real_slot:QWORD
.code

PUBLIC fnet_abortAiImg2imgJob
fnet_abortAiImg2imgJob PROC
    mov     rax, QWORD PTR [g_real_slot + 0*8]
    jmp     rax
fnet_abortAiImg2imgJob ENDP

PUBLIC fnet_abortAiModelJob
fnet_abortAiModelJob PROC
    mov     rax, QWORD PTR [g_real_slot + 1*8]
    jmp     rax
fnet_abortAiModelJob ENDP

PUBLIC fnet_abortAiTxt2imgJob
fnet_abortAiTxt2imgJob PROC
    mov     rax, QWORD PTR [g_real_slot + 2*8]
    jmp     rax
fnet_abortAiTxt2imgJob ENDP

PUBLIC fnet_abortAiTxt2txtJob
fnet_abortAiTxt2txtJob PROC
    mov     rax, QWORD PTR [g_real_slot + 3*8]
    jmp     rax
fnet_abortAiTxt2txtJob ENDP

PUBLIC fnet_addPrintListModel
fnet_addPrintListModel PROC
    mov     rax, QWORD PTR [g_real_slot + 4*8]
    jmp     rax
fnet_addPrintListModel ENDP

PUBLIC fnet_allocString
fnet_allocString PROC
    mov     rax, QWORD PTR [g_real_slot + 5*8]
    jmp     rax
fnet_allocString ENDP

PUBLIC fnet_bindAccountRelp
fnet_bindAccountRelp PROC
    mov     rax, QWORD PTR [g_real_slot + 6*8]
    jmp     rax
fnet_bindAccountRelp ENDP

PUBLIC fnet_bindWanDev
fnet_bindWanDev PROC
    mov     rax, QWORD PTR [g_real_slot + 7*8]
    jmp     rax
fnet_bindWanDev ENDP

PUBLIC fnet_cancelSliceTask
fnet_cancelSliceTask PROC
    mov     rax, QWORD PTR [g_real_slot + 8*8]
    jmp     rax
fnet_cancelSliceTask ENDP

PUBLIC fnet_configLanDevIndepMatl
fnet_configLanDevIndepMatl PROC
    mov     rax, QWORD PTR [g_real_slot + 9*8]
    jmp     rax
fnet_configLanDevIndepMatl ENDP

PUBLIC fnet_configLanDevMatlStation
fnet_configLanDevMatlStation PROC
    mov     rax, QWORD PTR [g_real_slot + 10*8]
    jmp     rax
fnet_configLanDevMatlStation ENDP

PUBLIC fnet_connectionSend
fnet_connectionSend PROC
    mov     rax, QWORD PTR [g_real_slot + 11*8]
    jmp     rax
fnet_connectionSend ENDP

PUBLIC fnet_connectionSendByHttp
fnet_connectionSendByHttp PROC
    mov     rax, QWORD PTR [g_real_slot + 12*8]
    jmp     rax
fnet_connectionSendByHttp ENDP

PUBLIC fnet_connectionSendMulti
fnet_connectionSendMulti PROC
    mov     rax, QWORD PTR [g_real_slot + 13*8]
    jmp     rax
fnet_connectionSendMulti ENDP

PUBLIC fnet_connectionSendMultiByHttp
fnet_connectionSendMultiByHttp PROC
    mov     rax, QWORD PTR [g_real_slot + 14*8]
    jmp     rax
fnet_connectionSendMultiByHttp ENDP

PUBLIC fnet_connectionStop
fnet_connectionStop PROC
    mov     rax, QWORD PTR [g_real_slot + 15*8]
    jmp     rax
fnet_connectionStop ENDP

PUBLIC fnet_connectionSubscribe
fnet_connectionSubscribe PROC
    mov     rax, QWORD PTR [g_real_slot + 16*8]
    jmp     rax
fnet_connectionSubscribe ENDP

PUBLIC fnet_connectionUnsubscribe
fnet_connectionUnsubscribe PROC
    mov     rax, QWORD PTR [g_real_slot + 17*8]
    jmp     rax
fnet_connectionUnsubscribe ENDP

PUBLIC fnet_createAiJobPipeline
fnet_createAiJobPipeline PROC
    mov     rax, QWORD PTR [g_real_slot + 18*8]
    jmp     rax
fnet_createAiJobPipeline ENDP

PUBLIC fnet_createConnection
fnet_createConnection PROC
    mov     rax, QWORD PTR [g_real_slot + 19*8]
    jmp     rax
fnet_createConnection ENDP

PUBLIC fnet_ctrlLanDevAirFilter
fnet_ctrlLanDevAirFilter PROC
    mov     rax, QWORD PTR [g_real_slot + 20*8]
    jmp     rax
fnet_ctrlLanDevAirFilter ENDP

PUBLIC fnet_ctrlLanDevClearFan
fnet_ctrlLanDevClearFan PROC
    mov     rax, QWORD PTR [g_real_slot + 21*8]
    jmp     rax
fnet_ctrlLanDevClearFan ENDP

PUBLIC fnet_ctrlLanDevErrorCode
fnet_ctrlLanDevErrorCode PROC
    mov     rax, QWORD PTR [g_real_slot + 22*8]
    jmp     rax
fnet_ctrlLanDevErrorCode ENDP

PUBLIC fnet_ctrlLanDevExtrude
fnet_ctrlLanDevExtrude PROC
    mov     rax, QWORD PTR [g_real_slot + 23*8]
    jmp     rax
fnet_ctrlLanDevExtrude ENDP

PUBLIC fnet_ctrlLanDevFirstLayerDetect
fnet_ctrlLanDevFirstLayerDetect PROC
    mov     rax, QWORD PTR [g_real_slot + 24*8]
    jmp     rax
fnet_ctrlLanDevFirstLayerDetect ENDP

PUBLIC fnet_ctrlLanDevHoming
fnet_ctrlLanDevHoming PROC
    mov     rax, QWORD PTR [g_real_slot + 25*8]
    jmp     rax
fnet_ctrlLanDevHoming ENDP

PUBLIC fnet_ctrlLanDevIndepMatl
fnet_ctrlLanDevIndepMatl PROC
    mov     rax, QWORD PTR [g_real_slot + 26*8]
    jmp     rax
fnet_ctrlLanDevIndepMatl ENDP

PUBLIC fnet_ctrlLanDevJob
fnet_ctrlLanDevJob PROC
    mov     rax, QWORD PTR [g_real_slot + 27*8]
    jmp     rax
fnet_ctrlLanDevJob ENDP

PUBLIC fnet_ctrlLanDevLight
fnet_ctrlLanDevLight PROC
    mov     rax, QWORD PTR [g_real_slot + 28*8]
    jmp     rax
fnet_ctrlLanDevLight ENDP

PUBLIC fnet_ctrlLanDevMatlStation
fnet_ctrlLanDevMatlStation PROC
    mov     rax, QWORD PTR [g_real_slot + 29*8]
    jmp     rax
fnet_ctrlLanDevMatlStation ENDP

PUBLIC fnet_ctrlLanDevMove
fnet_ctrlLanDevMove PROC
    mov     rax, QWORD PTR [g_real_slot + 30*8]
    jmp     rax
fnet_ctrlLanDevMove ENDP

PUBLIC fnet_ctrlLanDevPlateDetect
fnet_ctrlLanDevPlateDetect PROC
    mov     rax, QWORD PTR [g_real_slot + 31*8]
    jmp     rax
fnet_ctrlLanDevPlateDetect ENDP

PUBLIC fnet_ctrlLanDevPrint
fnet_ctrlLanDevPrint PROC
    mov     rax, QWORD PTR [g_real_slot + 32*8]
    jmp     rax
fnet_ctrlLanDevPrint ENDP

PUBLIC fnet_ctrlLanDevState
fnet_ctrlLanDevState PROC
    mov     rax, QWORD PTR [g_real_slot + 33*8]
    jmp     rax
fnet_ctrlLanDevState ENDP

PUBLIC fnet_ctrlLanDevTemp
fnet_ctrlLanDevTemp PROC
    mov     rax, QWORD PTR [g_real_slot + 34*8]
    jmp     rax
fnet_ctrlLanDevTemp ENDP

PUBLIC fnet_deleteSetting
fnet_deleteSetting PROC
    mov     rax, QWORD PTR [g_real_slot + 35*8]
    jmp     rax
fnet_deleteSetting ENDP

PUBLIC fnet_deleteTimeLapseVideo
fnet_deleteTimeLapseVideo PROC
    mov     rax, QWORD PTR [g_real_slot + 36*8]
    jmp     rax
fnet_deleteTimeLapseVideo ENDP

PUBLIC fnet_doBusGetRequest
fnet_doBusGetRequest PROC
    mov     rax, QWORD PTR [g_real_slot + 37*8]
    jmp     rax
fnet_doBusGetRequest ENDP

PUBLIC fnet_doBusPostRequest
fnet_doBusPostRequest PROC
    mov     rax, QWORD PTR [g_real_slot + 38*8]
    jmp     rax
fnet_doBusPostRequest ENDP

PUBLIC fnet_downloadFileDisk
fnet_downloadFileDisk PROC
    mov     rax, QWORD PTR [g_real_slot + 39*8]
    jmp     rax
fnet_downloadFileDisk ENDP

PUBLIC fnet_downloadFileMem
fnet_downloadFileMem PROC
    mov     rax, QWORD PTR [g_real_slot + 40*8]
    jmp     rax
fnet_downloadFileMem ENDP

PUBLIC fnet_freeAddCloudJobResults
fnet_freeAddCloudJobResults PROC
    mov     rax, QWORD PTR [g_real_slot + 41*8]
    jmp     rax
fnet_freeAddCloudJobResults ENDP

PUBLIC fnet_freeAddJobResult
fnet_freeAddJobResult PROC
    mov     rax, QWORD PTR [g_real_slot + 42*8]
    jmp     rax
fnet_freeAddJobResult ENDP

PUBLIC fnet_freeAiGeneralJobState
fnet_freeAiGeneralJobState PROC
    mov     rax, QWORD PTR [g_real_slot + 43*8]
    jmp     rax
fnet_freeAiGeneralJobState ENDP

PUBLIC fnet_freeAiJobPipelineInfo
fnet_freeAiJobPipelineInfo PROC
    mov     rax, QWORD PTR [g_real_slot + 44*8]
    jmp     rax
fnet_freeAiJobPipelineInfo ENDP

PUBLIC fnet_freeAiModelJobState
fnet_freeAiModelJobState PROC
    mov     rax, QWORD PTR [g_real_slot + 45*8]
    jmp     rax
fnet_freeAiModelJobState ENDP

PUBLIC fnet_freeBindAccountRelpResult
fnet_freeBindAccountRelpResult PROC
    mov     rax, QWORD PTR [g_real_slot + 46*8]
    jmp     rax
fnet_freeBindAccountRelpResult ENDP

PUBLIC fnet_freeBindData
fnet_freeBindData PROC
    mov     rax, QWORD PTR [g_real_slot + 47*8]
    jmp     rax
fnet_freeBindData ENDP

PUBLIC fnet_freeCloundFileData
fnet_freeCloundFileData PROC
    mov     rax, QWORD PTR [g_real_slot + 48*8]
    jmp     rax
fnet_freeCloundFileData ENDP

PUBLIC fnet_freeCloundGcodeData
fnet_freeCloundGcodeData PROC
    mov     rax, QWORD PTR [g_real_slot + 49*8]
    jmp     rax
fnet_freeCloundGcodeData ENDP

PUBLIC fnet_freeConnection
fnet_freeConnection PROC
    mov     rax, QWORD PTR [g_real_slot + 50*8]
    jmp     rax
fnet_freeConnection ENDP

PUBLIC fnet_freeDevDetail
fnet_freeDevDetail PROC
    mov     rax, QWORD PTR [g_real_slot + 51*8]
    jmp     rax
fnet_freeDevDetail ENDP

PUBLIC fnet_freeDevProduct
fnet_freeDevProduct PROC
    mov     rax, QWORD PTR [g_real_slot + 52*8]
    jmp     rax
fnet_freeDevProduct ENDP

PUBLIC fnet_freeFileData
fnet_freeFileData PROC
    mov     rax, QWORD PTR [g_real_slot + 53*8]
    jmp     rax
fnet_freeFileData ENDP

PUBLIC fnet_freeGcodeList
fnet_freeGcodeList PROC
    mov     rax, QWORD PTR [g_real_slot + 54*8]
    jmp     rax
fnet_freeGcodeList ENDP

PUBLIC fnet_freeJobInfo
fnet_freeJobInfo PROC
    mov     rax, QWORD PTR [g_real_slot + 55*8]
    jmp     rax
fnet_freeJobInfo ENDP

PUBLIC fnet_freeMqttConfig
fnet_freeMqttConfig PROC
    mov     rax, QWORD PTR [g_real_slot + 56*8]
    jmp     rax
fnet_freeMqttConfig ENDP

PUBLIC fnet_freeSliceState
fnet_freeSliceState PROC
    mov     rax, QWORD PTR [g_real_slot + 57*8]
    jmp     rax
fnet_freeSliceState ENDP

PUBLIC fnet_freeStartAiGeneralJobResult
fnet_freeStartAiGeneralJobResult PROC
    mov     rax, QWORD PTR [g_real_slot + 58*8]
    jmp     rax
fnet_freeStartAiGeneralJobResult ENDP

PUBLIC fnet_freeStartAiModelJobResult
fnet_freeStartAiModelJobResult PROC
    mov     rax, QWORD PTR [g_real_slot + 59*8]
    jmp     rax
fnet_freeStartAiModelJobResult ENDP

PUBLIC fnet_freeString
fnet_freeString PROC
    mov     rax, QWORD PTR [g_real_slot + 60*8]
    jmp     rax
fnet_freeString ENDP

PUBLIC fnet_freeSyncBindInfo
fnet_freeSyncBindInfo PROC
    mov     rax, QWORD PTR [g_real_slot + 61*8]
    jmp     rax
fnet_freeSyncBindInfo ENDP

PUBLIC fnet_freeSyncLoginInfo
fnet_freeSyncLoginInfo PROC
    mov     rax, QWORD PTR [g_real_slot + 62*8]
    jmp     rax
fnet_freeSyncLoginInfo ENDP

PUBLIC fnet_freeSyncOnlineInfo
fnet_freeSyncOnlineInfo PROC
    mov     rax, QWORD PTR [g_real_slot + 63*8]
    jmp     rax
fnet_freeSyncOnlineInfo ENDP

PUBLIC fnet_freeSystemMessage
fnet_freeSystemMessage PROC
    mov     rax, QWORD PTR [g_real_slot + 64*8]
    jmp     rax
fnet_freeSystemMessage ENDP

PUBLIC fnet_freeTimeLapseVideoList
fnet_freeTimeLapseVideoList PROC
    mov     rax, QWORD PTR [g_real_slot + 65*8]
    jmp     rax
fnet_freeTimeLapseVideoList ENDP

PUBLIC fnet_freeToken
fnet_freeToken PROC
    mov     rax, QWORD PTR [g_real_slot + 66*8]
    jmp     rax
fnet_freeToken ENDP

PUBLIC fnet_freeUploadLogInfo
fnet_freeUploadLogInfo PROC
    mov     rax, QWORD PTR [g_real_slot + 67*8]
    jmp     rax
fnet_freeUploadLogInfo ENDP

PUBLIC fnet_freeUserAiPointsInfo
fnet_freeUserAiPointsInfo PROC
    mov     rax, QWORD PTR [g_real_slot + 68*8]
    jmp     rax
fnet_freeUserAiPointsInfo ENDP

PUBLIC fnet_freeUserProfile
fnet_freeUserProfile PROC
    mov     rax, QWORD PTR [g_real_slot + 69*8]
    jmp     rax
fnet_freeUserProfile ENDP

PUBLIC fnet_freeWanDevList
fnet_freeWanDevList PROC
    mov     rax, QWORD PTR [g_real_slot + 70*8]
    jmp     rax
fnet_freeWanDevList ENDP

PUBLIC fnet_freeWriteMultiResult
fnet_freeWriteMultiResult PROC
    mov     rax, QWORD PTR [g_real_slot + 71*8]
    jmp     rax
fnet_freeWriteMultiResult ENDP

PUBLIC fnet_getAiImg2imgJobState
fnet_getAiImg2imgJobState PROC
    mov     rax, QWORD PTR [g_real_slot + 72*8]
    jmp     rax
fnet_getAiImg2imgJobState ENDP

PUBLIC fnet_getAiModelJobState
fnet_getAiModelJobState PROC
    mov     rax, QWORD PTR [g_real_slot + 73*8]
    jmp     rax
fnet_getAiModelJobState ENDP

PUBLIC fnet_getAiTxt2imgJobState
fnet_getAiTxt2imgJobState PROC
    mov     rax, QWORD PTR [g_real_slot + 74*8]
    jmp     rax
fnet_getAiTxt2imgJobState ENDP

PUBLIC fnet_getAiTxt2txtJobState
fnet_getAiTxt2txtJobState PROC
    mov     rax, QWORD PTR [g_real_slot + 75*8]
    jmp     rax
fnet_getAiTxt2txtJobState ENDP

PUBLIC fnet_getBusComUrl
fnet_getBusComUrl PROC
    mov     rax, QWORD PTR [g_real_slot + 76*8]
    jmp     rax
fnet_getBusComUrl ENDP

PUBLIC fnet_getExistingAiModelJob
fnet_getExistingAiModelJob PROC
    mov     rax, QWORD PTR [g_real_slot + 77*8]
    jmp     rax
fnet_getExistingAiModelJob ENDP

PUBLIC fnet_getHomePageUrl
fnet_getHomePageUrl PROC
    mov     rax, QWORD PTR [g_real_slot + 78*8]
    jmp     rax
fnet_getHomePageUrl ENDP

PUBLIC fnet_getLanDevDetail
fnet_getLanDevDetail PROC
    mov     rax, QWORD PTR [g_real_slot + 79*8]
    jmp     rax
fnet_getLanDevDetail ENDP

PUBLIC fnet_getLanDevGcodeList
fnet_getLanDevGcodeList PROC
    mov     rax, QWORD PTR [g_real_slot + 80*8]
    jmp     rax
fnet_getLanDevGcodeList ENDP

PUBLIC fnet_getLanDevGcodeThumb
fnet_getLanDevGcodeThumb PROC
    mov     rax, QWORD PTR [g_real_slot + 81*8]
    jmp     rax
fnet_getLanDevGcodeThumb ENDP

PUBLIC fnet_getLanDevProduct
fnet_getLanDevProduct PROC
    mov     rax, QWORD PTR [g_real_slot + 82*8]
    jmp     rax
fnet_getLanDevProduct ENDP

PUBLIC fnet_getMonitorMessage
fnet_getMonitorMessage PROC
    mov     rax, QWORD PTR [g_real_slot + 83*8]
    jmp     rax
fnet_getMonitorMessage ENDP

PUBLIC fnet_getMqttConfig
fnet_getMqttConfig PROC
    mov     rax, QWORD PTR [g_real_slot + 84*8]
    jmp     rax
fnet_getMqttConfig ENDP

PUBLIC fnet_getSettingList
fnet_getSettingList PROC
    mov     rax, QWORD PTR [g_real_slot + 85*8]
    jmp     rax
fnet_getSettingList ENDP

PUBLIC fnet_getSettingList2
fnet_getSettingList2 PROC
    mov     rax, QWORD PTR [g_real_slot + 86*8]
    jmp     rax
fnet_getSettingList2 ENDP

PUBLIC fnet_getSystemMessage
fnet_getSystemMessage PROC
    mov     rax, QWORD PTR [g_real_slot + 87*8]
    jmp     rax
fnet_getSystemMessage ENDP

PUBLIC fnet_getTokenByPassword
fnet_getTokenByPassword PROC
    mov     rax, QWORD PTR [g_real_slot + 88*8]
    jmp     rax
fnet_getTokenByPassword ENDP

PUBLIC fnet_getTokenBySMSCode
fnet_getTokenBySMSCode PROC
    mov     rax, QWORD PTR [g_real_slot + 89*8]
    jmp     rax
fnet_getTokenBySMSCode ENDP

PUBLIC fnet_getUpdateComUrl
fnet_getUpdateComUrl PROC
    mov     rax, QWORD PTR [g_real_slot + 90*8]
    jmp     rax
fnet_getUpdateComUrl ENDP

PUBLIC fnet_getUserAiPointsInfo
fnet_getUserAiPointsInfo PROC
    mov     rax, QWORD PTR [g_real_slot + 91*8]
    jmp     rax
fnet_getUserAiPointsInfo ENDP

PUBLIC fnet_getUserPresets
fnet_getUserPresets PROC
    mov     rax, QWORD PTR [g_real_slot + 92*8]
    jmp     rax
fnet_getUserPresets ENDP

PUBLIC fnet_getUserProfile
fnet_getUserProfile PROC
    mov     rax, QWORD PTR [g_real_slot + 93*8]
    jmp     rax
fnet_getUserProfile ENDP

PUBLIC fnet_getVersion
fnet_getVersion PROC
    mov     rax, QWORD PTR [g_real_slot + 94*8]
    jmp     rax
fnet_getVersion ENDP

PUBLIC fnet_getWanDevGcodeList
fnet_getWanDevGcodeList PROC
    mov     rax, QWORD PTR [g_real_slot + 95*8]
    jmp     rax
fnet_getWanDevGcodeList ENDP

PUBLIC fnet_getWanDevList
fnet_getWanDevList PROC
    mov     rax, QWORD PTR [g_real_slot + 96*8]
    jmp     rax
fnet_getWanDevList ENDP

PUBLIC fnet_getWanDevProductDetail
fnet_getWanDevProductDetail PROC
    mov     rax, QWORD PTR [g_real_slot + 97*8]
    jmp     rax
fnet_getWanDevProductDetail ENDP

PUBLIC fnet_getWanDevTimeLapseVideoList
fnet_getWanDevTimeLapseVideoList PROC
    mov     rax, QWORD PTR [g_real_slot + 98*8]
    jmp     rax
fnet_getWanDevTimeLapseVideoList ENDP

PUBLIC fnet_initlize
fnet_initlize PROC
    mov     rax, QWORD PTR [g_real_slot + 99*8]
    jmp     rax
fnet_initlize ENDP

PUBLIC fnet_lanDevSendGcode
fnet_lanDevSendGcode PROC
    mov     rax, QWORD PTR [g_real_slot + 100*8]
    jmp     rax
fnet_lanDevSendGcode ENDP

PUBLIC fnet_lanDevStartJob
fnet_lanDevStartJob PROC
    mov     rax, QWORD PTR [g_real_slot + 101*8]
    jmp     rax
fnet_lanDevStartJob ENDP

PUBLIC fnet_navLikeModel
fnet_navLikeModel PROC
    mov     rax, QWORD PTR [g_real_slot + 102*8]
    jmp     rax
fnet_navLikeModel ENDP

PUBLIC fnet_notifyLanDevWanBind
fnet_notifyLanDevWanBind PROC
    mov     rax, QWORD PTR [g_real_slot + 103*8]
    jmp     rax
fnet_notifyLanDevWanBind ENDP

PUBLIC fnet_postReadSystemMessage
fnet_postReadSystemMessage PROC
    mov     rax, QWORD PTR [g_real_slot + 104*8]
    jmp     rax
fnet_postReadSystemMessage ENDP

PUBLIC fnet_putSetting
fnet_putSetting PROC
    mov     rax, QWORD PTR [g_real_slot + 105*8]
    jmp     rax
fnet_putSetting ENDP

PUBLIC fnet_refreshToken
fnet_refreshToken PROC
    mov     rax, QWORD PTR [g_real_slot + 106*8]
    jmp     rax
fnet_refreshToken ENDP

PUBLIC fnet_removePrintListModel
fnet_removePrintListModel PROC
    mov     rax, QWORD PTR [g_real_slot + 107*8]
    jmp     rax
fnet_removePrintListModel ENDP

PUBLIC fnet_reportModel
fnet_reportModel PROC
    mov     rax, QWORD PTR [g_real_slot + 108*8]
    jmp     rax
fnet_reportModel ENDP

PUBLIC fnet_reportTrackingData
fnet_reportTrackingData PROC
    mov     rax, QWORD PTR [g_real_slot + 109*8]
    jmp     rax
fnet_reportTrackingData ENDP

PUBLIC fnet_reportTrackingDataBatch
fnet_reportTrackingDataBatch PROC
    mov     rax, QWORD PTR [g_real_slot + 110*8]
    jmp     rax
fnet_reportTrackingDataBatch ENDP

PUBLIC fnet_requestSettingId
fnet_requestSettingId PROC
    mov     rax, QWORD PTR [g_real_slot + 111*8]
    jmp     rax
fnet_requestSettingId ENDP

PUBLIC fnet_retrySliceTask
fnet_retrySliceTask PROC
    mov     rax, QWORD PTR [g_real_slot + 112*8]
    jmp     rax
fnet_retrySliceTask ENDP

PUBLIC fnet_sendSMSCode
fnet_sendSMSCode PROC
    mov     rax, QWORD PTR [g_real_slot + 113*8]
    jmp     rax
fnet_sendSMSCode ENDP

PUBLIC fnet_setUserAgent
fnet_setUserAgent PROC
    mov     rax, QWORD PTR [g_real_slot + 114*8]
    jmp     rax
fnet_setUserAgent ENDP

PUBLIC fnet_signOut
fnet_signOut PROC
    mov     rax, QWORD PTR [g_real_slot + 115*8]
    jmp     rax
fnet_signOut ENDP

PUBLIC fnet_startAiImg2imgJob
fnet_startAiImg2imgJob PROC
    mov     rax, QWORD PTR [g_real_slot + 116*8]
    jmp     rax
fnet_startAiImg2imgJob ENDP

PUBLIC fnet_startAiModelJob
fnet_startAiModelJob PROC
    mov     rax, QWORD PTR [g_real_slot + 117*8]
    jmp     rax
fnet_startAiModelJob ENDP

PUBLIC fnet_startAiTxt2imgJob
fnet_startAiTxt2imgJob PROC
    mov     rax, QWORD PTR [g_real_slot + 118*8]
    jmp     rax
fnet_startAiTxt2imgJob ENDP

PUBLIC fnet_startAiTxt2txtJob
fnet_startAiTxt2txtJob PROC
    mov     rax, QWORD PTR [g_real_slot + 119*8]
    jmp     rax
fnet_startAiTxt2txtJob ENDP

PUBLIC fnet_unbindWanDev
fnet_unbindWanDev PROC
    mov     rax, QWORD PTR [g_real_slot + 120*8]
    jmp     rax
fnet_unbindWanDev ENDP

PUBLIC fnet_uninitlize
fnet_uninitlize PROC
    mov     rax, QWORD PTR [g_real_slot + 121*8]
    jmp     rax
fnet_uninitlize ENDP

PUBLIC fnet_uploadAiImageClound
fnet_uploadAiImageClound PROC
    mov     rax, QWORD PTR [g_real_slot + 122*8]
    jmp     rax
fnet_uploadAiImageClound ENDP

PUBLIC fnet_uploadLogFileCloud
fnet_uploadLogFileCloud PROC
    mov     rax, QWORD PTR [g_real_slot + 123*8]
    jmp     rax
fnet_uploadLogFileCloud ENDP

PUBLIC fnet_uploadLogFileCloudEx
fnet_uploadLogFileCloudEx PROC
    mov     rax, QWORD PTR [g_real_slot + 124*8]
    jmp     rax
fnet_uploadLogFileCloudEx ENDP

PUBLIC fnet_userClickCount
fnet_userClickCount PROC
    mov     rax, QWORD PTR [g_real_slot + 125*8]
    jmp     rax
fnet_userClickCount ENDP

PUBLIC fnet_wanDevAddCloundJob
fnet_wanDevAddCloundJob PROC
    mov     rax, QWORD PTR [g_real_slot + 126*8]
    jmp     rax
fnet_wanDevAddCloundJob ENDP

PUBLIC fnet_wanDevAddJob
fnet_wanDevAddJob PROC
    mov     rax, QWORD PTR [g_real_slot + 127*8]
    jmp     rax
fnet_wanDevAddJob ENDP

PUBLIC fnet_wanDevSendGcodeClound
fnet_wanDevSendGcodeClound PROC
    mov     rax, QWORD PTR [g_real_slot + 128*8]
    jmp     rax
fnet_wanDevSendGcodeClound ENDP

END
