#ifndef FLASHNET_FORWARDS_H
#define FLASHNET_FORWARDS_H

/* AUTO-GENERATED by tools/gen_forwards.py -- do not edit */

#ifdef __cplusplus
extern "C" {
#endif

void fnet_abortAiImg2imgJob(void);
void fnet_abortAiModelJob(void);
void fnet_abortAiTxt2imgJob(void);
void fnet_abortAiTxt2txtJob(void);
void fnet_addPrintListModel(void);
void fnet_allocString(void);
void fnet_bindAccountRelp(void);
void fnet_bindWanDev(void);
void fnet_cancelSliceTask(void);
void fnet_configLanDevIndepMatl(void);
void fnet_configLanDevMatlStation(void);
void fnet_connectionSend(void);
void fnet_connectionSendByHttp(void);
void fnet_connectionSendMulti(void);
void fnet_connectionSendMultiByHttp(void);
void fnet_connectionStop(void);
void fnet_connectionSubscribe(void);
void fnet_connectionUnsubscribe(void);
void fnet_createAiJobPipeline(void);
void fnet_createConnection(void);
void fnet_ctrlLanDevAirFilter(void);
void fnet_ctrlLanDevClearFan(void);
void fnet_ctrlLanDevErrorCode(void);
void fnet_ctrlLanDevExtrude(void);
void fnet_ctrlLanDevFirstLayerDetect(void);
void fnet_ctrlLanDevHoming(void);
void fnet_ctrlLanDevIndepMatl(void);
void fnet_ctrlLanDevJob(void);
void fnet_ctrlLanDevLight(void);
void fnet_ctrlLanDevMatlStation(void);
void fnet_ctrlLanDevMove(void);
void fnet_ctrlLanDevPlateDetect(void);
void fnet_ctrlLanDevPrint(void);
void fnet_ctrlLanDevState(void);
void fnet_ctrlLanDevTemp(void);
void fnet_deleteSetting(void);
void fnet_deleteTimeLapseVideo(void);
void fnet_doBusGetRequest(void);
void fnet_doBusPostRequest(void);
void fnet_downloadFileDisk(void);
void fnet_downloadFileMem(void);
void fnet_freeAddCloudJobResults(void);
void fnet_freeAddJobResult(void);
void fnet_freeAiGeneralJobState(void);
void fnet_freeAiJobPipelineInfo(void);
void fnet_freeAiModelJobState(void);
void fnet_freeBindAccountRelpResult(void);
void fnet_freeBindData(void);
void fnet_freeCloundFileData(void);
void fnet_freeCloundGcodeData(void);
void fnet_freeConnection(void);
void fnet_freeDevDetail(void);
void fnet_freeDevProduct(void);
void fnet_freeFileData(void);
void fnet_freeGcodeList(void);
void fnet_freeJobInfo(void);
void fnet_freeMqttConfig(void);
void fnet_freeSliceState(void);
void fnet_freeStartAiGeneralJobResult(void);
void fnet_freeStartAiModelJobResult(void);
void fnet_freeString(void);
void fnet_freeSyncBindInfo(void);
void fnet_freeSyncLoginInfo(void);
void fnet_freeSyncOnlineInfo(void);
void fnet_freeSystemMessage(void);
void fnet_freeTimeLapseVideoList(void);
void fnet_freeToken(void);
void fnet_freeUploadLogInfo(void);
void fnet_freeUserAiPointsInfo(void);
void fnet_freeUserProfile(void);
void fnet_freeWanDevList(void);
void fnet_freeWriteMultiResult(void);
void fnet_getAiImg2imgJobState(void);
void fnet_getAiModelJobState(void);
void fnet_getAiTxt2imgJobState(void);
void fnet_getAiTxt2txtJobState(void);
void fnet_getBusComUrl(void);
void fnet_getExistingAiModelJob(void);
void fnet_getHomePageUrl(void);
void fnet_getLanDevDetail(void);
void fnet_getLanDevGcodeList(void);
void fnet_getLanDevGcodeThumb(void);
void fnet_getLanDevProduct(void);
void fnet_getMonitorMessage(void);
void fnet_getMqttConfig(void);
void fnet_getSettingList(void);
void fnet_getSettingList2(void);
void fnet_getSystemMessage(void);
void fnet_getTokenByPassword(void);
void fnet_getTokenBySMSCode(void);
void fnet_getUpdateComUrl(void);
void fnet_getUserAiPointsInfo(void);
void fnet_getUserPresets(void);
void fnet_getUserProfile(void);
void fnet_getVersion(void);
void fnet_getWanDevGcodeList(void);
void fnet_getWanDevList(void);
void fnet_getWanDevProductDetail(void);
void fnet_getWanDevTimeLapseVideoList(void);
void fnet_initlize(void);
void fnet_lanDevSendGcode(void);
void fnet_lanDevStartJob(void);
void fnet_navLikeModel(void);
void fnet_notifyLanDevWanBind(void);
void fnet_postReadSystemMessage(void);
void fnet_putSetting(void);
void fnet_refreshToken(void);
void fnet_removePrintListModel(void);
void fnet_reportModel(void);
void fnet_reportTrackingData(void);
void fnet_reportTrackingDataBatch(void);
void fnet_requestSettingId(void);
void fnet_retrySliceTask(void);
void fnet_sendSMSCode(void);
void fnet_setUserAgent(void);
void fnet_signOut(void);
void fnet_startAiImg2imgJob(void);
void fnet_startAiModelJob(void);
void fnet_startAiTxt2imgJob(void);
void fnet_startAiTxt2txtJob(void);
void fnet_unbindWanDev(void);
void fnet_uninitlize(void);
void fnet_uploadAiImageClound(void);
void fnet_uploadLogFileCloud(void);
void fnet_uploadLogFileCloudEx(void);
void fnet_userClickCount(void);
void fnet_wanDevAddCloundJob(void);
void fnet_wanDevAddJob(void);
void fnet_wanDevSendGcodeClound(void);

extern void *g_real_slot[];
enum {
    SLOT_fnet_abortAiImg2imgJob = 0,
    SLOT_fnet_abortAiModelJob = 1,
    SLOT_fnet_abortAiTxt2imgJob = 2,
    SLOT_fnet_abortAiTxt2txtJob = 3,
    SLOT_fnet_addPrintListModel = 4,
    SLOT_fnet_allocString = 5,
    SLOT_fnet_bindAccountRelp = 6,
    SLOT_fnet_bindWanDev = 7,
    SLOT_fnet_cancelSliceTask = 8,
    SLOT_fnet_configLanDevIndepMatl = 9,
    SLOT_fnet_configLanDevMatlStation = 10,
    SLOT_fnet_connectionSend = 11,
    SLOT_fnet_connectionSendByHttp = 12,
    SLOT_fnet_connectionSendMulti = 13,
    SLOT_fnet_connectionSendMultiByHttp = 14,
    SLOT_fnet_connectionStop = 15,
    SLOT_fnet_connectionSubscribe = 16,
    SLOT_fnet_connectionUnsubscribe = 17,
    SLOT_fnet_createAiJobPipeline = 18,
    SLOT_fnet_createConnection = 19,
    SLOT_fnet_ctrlLanDevAirFilter = 20,
    SLOT_fnet_ctrlLanDevClearFan = 21,
    SLOT_fnet_ctrlLanDevErrorCode = 22,
    SLOT_fnet_ctrlLanDevExtrude = 23,
    SLOT_fnet_ctrlLanDevFirstLayerDetect = 24,
    SLOT_fnet_ctrlLanDevHoming = 25,
    SLOT_fnet_ctrlLanDevIndepMatl = 26,
    SLOT_fnet_ctrlLanDevJob = 27,
    SLOT_fnet_ctrlLanDevLight = 28,
    SLOT_fnet_ctrlLanDevMatlStation = 29,
    SLOT_fnet_ctrlLanDevMove = 30,
    SLOT_fnet_ctrlLanDevPlateDetect = 31,
    SLOT_fnet_ctrlLanDevPrint = 32,
    SLOT_fnet_ctrlLanDevState = 33,
    SLOT_fnet_ctrlLanDevTemp = 34,
    SLOT_fnet_deleteSetting = 35,
    SLOT_fnet_deleteTimeLapseVideo = 36,
    SLOT_fnet_doBusGetRequest = 37,
    SLOT_fnet_doBusPostRequest = 38,
    SLOT_fnet_downloadFileDisk = 39,
    SLOT_fnet_downloadFileMem = 40,
    SLOT_fnet_freeAddCloudJobResults = 41,
    SLOT_fnet_freeAddJobResult = 42,
    SLOT_fnet_freeAiGeneralJobState = 43,
    SLOT_fnet_freeAiJobPipelineInfo = 44,
    SLOT_fnet_freeAiModelJobState = 45,
    SLOT_fnet_freeBindAccountRelpResult = 46,
    SLOT_fnet_freeBindData = 47,
    SLOT_fnet_freeCloundFileData = 48,
    SLOT_fnet_freeCloundGcodeData = 49,
    SLOT_fnet_freeConnection = 50,
    SLOT_fnet_freeDevDetail = 51,
    SLOT_fnet_freeDevProduct = 52,
    SLOT_fnet_freeFileData = 53,
    SLOT_fnet_freeGcodeList = 54,
    SLOT_fnet_freeJobInfo = 55,
    SLOT_fnet_freeMqttConfig = 56,
    SLOT_fnet_freeSliceState = 57,
    SLOT_fnet_freeStartAiGeneralJobResult = 58,
    SLOT_fnet_freeStartAiModelJobResult = 59,
    SLOT_fnet_freeString = 60,
    SLOT_fnet_freeSyncBindInfo = 61,
    SLOT_fnet_freeSyncLoginInfo = 62,
    SLOT_fnet_freeSyncOnlineInfo = 63,
    SLOT_fnet_freeSystemMessage = 64,
    SLOT_fnet_freeTimeLapseVideoList = 65,
    SLOT_fnet_freeToken = 66,
    SLOT_fnet_freeUploadLogInfo = 67,
    SLOT_fnet_freeUserAiPointsInfo = 68,
    SLOT_fnet_freeUserProfile = 69,
    SLOT_fnet_freeWanDevList = 70,
    SLOT_fnet_freeWriteMultiResult = 71,
    SLOT_fnet_getAiImg2imgJobState = 72,
    SLOT_fnet_getAiModelJobState = 73,
    SLOT_fnet_getAiTxt2imgJobState = 74,
    SLOT_fnet_getAiTxt2txtJobState = 75,
    SLOT_fnet_getBusComUrl = 76,
    SLOT_fnet_getExistingAiModelJob = 77,
    SLOT_fnet_getHomePageUrl = 78,
    SLOT_fnet_getLanDevDetail = 79,
    SLOT_fnet_getLanDevGcodeList = 80,
    SLOT_fnet_getLanDevGcodeThumb = 81,
    SLOT_fnet_getLanDevProduct = 82,
    SLOT_fnet_getMonitorMessage = 83,
    SLOT_fnet_getMqttConfig = 84,
    SLOT_fnet_getSettingList = 85,
    SLOT_fnet_getSettingList2 = 86,
    SLOT_fnet_getSystemMessage = 87,
    SLOT_fnet_getTokenByPassword = 88,
    SLOT_fnet_getTokenBySMSCode = 89,
    SLOT_fnet_getUpdateComUrl = 90,
    SLOT_fnet_getUserAiPointsInfo = 91,
    SLOT_fnet_getUserPresets = 92,
    SLOT_fnet_getUserProfile = 93,
    SLOT_fnet_getVersion = 94,
    SLOT_fnet_getWanDevGcodeList = 95,
    SLOT_fnet_getWanDevList = 96,
    SLOT_fnet_getWanDevProductDetail = 97,
    SLOT_fnet_getWanDevTimeLapseVideoList = 98,
    SLOT_fnet_initlize = 99,
    SLOT_fnet_lanDevSendGcode = 100,
    SLOT_fnet_lanDevStartJob = 101,
    SLOT_fnet_navLikeModel = 102,
    SLOT_fnet_notifyLanDevWanBind = 103,
    SLOT_fnet_postReadSystemMessage = 104,
    SLOT_fnet_putSetting = 105,
    SLOT_fnet_refreshToken = 106,
    SLOT_fnet_removePrintListModel = 107,
    SLOT_fnet_reportModel = 108,
    SLOT_fnet_reportTrackingData = 109,
    SLOT_fnet_reportTrackingDataBatch = 110,
    SLOT_fnet_requestSettingId = 111,
    SLOT_fnet_retrySliceTask = 112,
    SLOT_fnet_sendSMSCode = 113,
    SLOT_fnet_setUserAgent = 114,
    SLOT_fnet_signOut = 115,
    SLOT_fnet_startAiImg2imgJob = 116,
    SLOT_fnet_startAiModelJob = 117,
    SLOT_fnet_startAiTxt2imgJob = 118,
    SLOT_fnet_startAiTxt2txtJob = 119,
    SLOT_fnet_unbindWanDev = 120,
    SLOT_fnet_uninitlize = 121,
    SLOT_fnet_uploadAiImageClound = 122,
    SLOT_fnet_uploadLogFileCloud = 123,
    SLOT_fnet_uploadLogFileCloudEx = 124,
    SLOT_fnet_userClickCount = 125,
    SLOT_fnet_wanDevAddCloundJob = 126,
    SLOT_fnet_wanDevAddJob = 127,
    SLOT_fnet_wanDevSendGcodeClound = 128,
};

#define FORWARDED_COUNT 129
#define FORWARDED_NAMES \
    "fnet_abortAiImg2imgJob", \
    "fnet_abortAiModelJob", \
    "fnet_abortAiTxt2imgJob", \
    "fnet_abortAiTxt2txtJob", \
    "fnet_addPrintListModel", \
    "fnet_allocString", \
    "fnet_bindAccountRelp", \
    "fnet_bindWanDev", \
    "fnet_cancelSliceTask", \
    "fnet_configLanDevIndepMatl", \
    "fnet_configLanDevMatlStation", \
    "fnet_connectionSend", \
    "fnet_connectionSendByHttp", \
    "fnet_connectionSendMulti", \
    "fnet_connectionSendMultiByHttp", \
    "fnet_connectionStop", \
    "fnet_connectionSubscribe", \
    "fnet_connectionUnsubscribe", \
    "fnet_createAiJobPipeline", \
    "fnet_createConnection", \
    "fnet_ctrlLanDevAirFilter", \
    "fnet_ctrlLanDevClearFan", \
    "fnet_ctrlLanDevErrorCode", \
    "fnet_ctrlLanDevExtrude", \
    "fnet_ctrlLanDevFirstLayerDetect", \
    "fnet_ctrlLanDevHoming", \
    "fnet_ctrlLanDevIndepMatl", \
    "fnet_ctrlLanDevJob", \
    "fnet_ctrlLanDevLight", \
    "fnet_ctrlLanDevMatlStation", \
    "fnet_ctrlLanDevMove", \
    "fnet_ctrlLanDevPlateDetect", \
    "fnet_ctrlLanDevPrint", \
    "fnet_ctrlLanDevState", \
    "fnet_ctrlLanDevTemp", \
    "fnet_deleteSetting", \
    "fnet_deleteTimeLapseVideo", \
    "fnet_doBusGetRequest", \
    "fnet_doBusPostRequest", \
    "fnet_downloadFileDisk", \
    "fnet_downloadFileMem", \
    "fnet_freeAddCloudJobResults", \
    "fnet_freeAddJobResult", \
    "fnet_freeAiGeneralJobState", \
    "fnet_freeAiJobPipelineInfo", \
    "fnet_freeAiModelJobState", \
    "fnet_freeBindAccountRelpResult", \
    "fnet_freeBindData", \
    "fnet_freeCloundFileData", \
    "fnet_freeCloundGcodeData", \
    "fnet_freeConnection", \
    "fnet_freeDevDetail", \
    "fnet_freeDevProduct", \
    "fnet_freeFileData", \
    "fnet_freeGcodeList", \
    "fnet_freeJobInfo", \
    "fnet_freeMqttConfig", \
    "fnet_freeSliceState", \
    "fnet_freeStartAiGeneralJobResult", \
    "fnet_freeStartAiModelJobResult", \
    "fnet_freeString", \
    "fnet_freeSyncBindInfo", \
    "fnet_freeSyncLoginInfo", \
    "fnet_freeSyncOnlineInfo", \
    "fnet_freeSystemMessage", \
    "fnet_freeTimeLapseVideoList", \
    "fnet_freeToken", \
    "fnet_freeUploadLogInfo", \
    "fnet_freeUserAiPointsInfo", \
    "fnet_freeUserProfile", \
    "fnet_freeWanDevList", \
    "fnet_freeWriteMultiResult", \
    "fnet_getAiImg2imgJobState", \
    "fnet_getAiModelJobState", \
    "fnet_getAiTxt2imgJobState", \
    "fnet_getAiTxt2txtJobState", \
    "fnet_getBusComUrl", \
    "fnet_getExistingAiModelJob", \
    "fnet_getHomePageUrl", \
    "fnet_getLanDevDetail", \
    "fnet_getLanDevGcodeList", \
    "fnet_getLanDevGcodeThumb", \
    "fnet_getLanDevProduct", \
    "fnet_getMonitorMessage", \
    "fnet_getMqttConfig", \
    "fnet_getSettingList", \
    "fnet_getSettingList2", \
    "fnet_getSystemMessage", \
    "fnet_getTokenByPassword", \
    "fnet_getTokenBySMSCode", \
    "fnet_getUpdateComUrl", \
    "fnet_getUserAiPointsInfo", \
    "fnet_getUserPresets", \
    "fnet_getUserProfile", \
    "fnet_getVersion", \
    "fnet_getWanDevGcodeList", \
    "fnet_getWanDevList", \
    "fnet_getWanDevProductDetail", \
    "fnet_getWanDevTimeLapseVideoList", \
    "fnet_initlize", \
    "fnet_lanDevSendGcode", \
    "fnet_lanDevStartJob", \
    "fnet_navLikeModel", \
    "fnet_notifyLanDevWanBind", \
    "fnet_postReadSystemMessage", \
    "fnet_putSetting", \
    "fnet_refreshToken", \
    "fnet_removePrintListModel", \
    "fnet_reportModel", \
    "fnet_reportTrackingData", \
    "fnet_reportTrackingDataBatch", \
    "fnet_requestSettingId", \
    "fnet_retrySliceTask", \
    "fnet_sendSMSCode", \
    "fnet_setUserAgent", \
    "fnet_signOut", \
    "fnet_startAiImg2imgJob", \
    "fnet_startAiModelJob", \
    "fnet_startAiTxt2imgJob", \
    "fnet_startAiTxt2txtJob", \
    "fnet_unbindWanDev", \
    "fnet_uninitlize", \
    "fnet_uploadAiImageClound", \
    "fnet_uploadLogFileCloud", \
    "fnet_uploadLogFileCloudEx", \
    "fnet_userClickCount", \
    "fnet_wanDevAddCloundJob", \
    "fnet_wanDevAddJob", \
    "fnet_wanDevSendGcodeClound", \
    NULL

#ifdef __cplusplus
}
#endif

#endif
