"""Generate the forwarding layer for the FlashNetwork.dll shim.

We intercept exactly one export (fnet_getLanDevList) plus its free function.
Every other export must reach the real DLL byte-for-byte, with its real
signature, so nothing else changes behaviour.

MSVC x64 has no inline asm, so instead of per-signature wrappers we emit a
single naked trampoline per symbol that reads the real pointer from a table
slot and jumps to it. That preserves every register and the stack exactly as
the caller set it up, which is what a genuine forwarder must do.

  __declspec(naked) exported_Trampoline:
      movq    g_real_slot(%rip), %rax
      jmp     *%rax

The slot is filled by flashnet_shim.c at load time.
"""
import pathlib
import re
import subprocess

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
DLL = pathlib.Path(r"C:\Program Files\Flashforge\Flash Studio Desktop\FlashNetwork.dll")
READOBJ = r"C:\Program Files\LLVM\bin\llvm-readobj.exe"

# implemented by hand in flashnet_shim.c
OWN = {"fnet_getLanDevList", "fnet_freeLanDevInfos"}


def exports():
    out = subprocess.run([READOBJ, "--coff-exports", str(DLL)],
                         capture_output=True, text=True, check=True).stdout
    return sorted({m.group(1) for m in re.finditer(r"Name:\s*(fnet_\S+)", out)})


def main():
    names = exports()
    fwd = [n for n in names if n not in OWN]
    print(f"exports={len(names)} own={len(OWN)} forwarding={len(fwd)}")

    # ---- header ----
    h = ROOT / "flashnet_forwards.h"
    with h.open("w", encoding="utf-8") as f:
        f.write("#ifndef FLASHNET_FORWARDS_H\n#define FLASHNET_FORWARDS_H\n\n")
        f.write("/* AUTO-GENERATED by tools/gen_forwards.py -- do not edit */\n\n")
        f.write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
        for n in fwd:
            f.write(f"void {n}(void);\n")
        f.write("\nextern void *g_real_slot[];\n")
        f.write("enum {\n")
        for i, n in enumerate(fwd):
            f.write(f"    SLOT_{n} = {i},\n")
        f.write("};\n\n")
        # name table consumed by shim_init()
        f.write("#define FORWARDED_COUNT %d\n" % len(fwd))
        f.write("#define FORWARDED_NAMES \\\n")
        for n in fwd:
            f.write(f'    "{n}", \\\n')
        f.write("    NULL\n")
        f.write("\n#ifdef __cplusplus\n}\n#endif\n\n#endif\n")

    # ---- .asm ----
    a = ROOT / "flashnet_forwards.asm"
    with a.open("w", encoding="utf-8") as f:
        f.write("; AUTO-GENERATED by tools/gen_forwards.py -- do not edit\n")
        f.write("; One naked trampoline per forwarded export.\n")
        f.write("EXTERN g_real_slot:QWORD\n")
        f.write(".code\n\n")
        for n in fwd:
            f.write(f"PUBLIC {n}\n")
            f.write(f"{n} PROC\n")
            f.write(f"    mov     rax, QWORD PTR [g_real_slot + {fwd.index(n)}*8]\n")
            f.write("    jmp     rax\n")
            f.write(f"{n} ENDP\n\n")
        f.write("END\n")

    print(f"wrote {h.name} and {a.name}")


if __name__ == "__main__":
    main()
